# Generated by Django 2.1 on 2018-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='posttaskquestionnaire',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pretaskquestionnaire',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='testperson',
            options={'managed': False},
        ),
    ]
