# Generated by Django 2.1 on 2018-12-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_tracking', '0002_testperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretaskQuestionnaire',
            fields=[
                ('pretask', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('answer_one', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pretask_questionnaire',
                'managed': False,
            },
        ),
    ]
