# Generated by Django 2.1 on 2018-12-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_tracking', '0003_pretaskquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosttaskQuestionnaire',
            fields=[
                ('posttask_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('selected_answer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posttask_questionnaire',
                'managed': False,
            },
        ),
    ]
